
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadena = 13;
  public static final int iguala = 17;
  public static final int imprime = 4;
  public static final int por = 8;
  public static final int finSent = 5;
  public static final int cierra_parentesis = 16;
  public static final int substra = 20;
  public static final int menos = 7;
  public static final int menor = 19;
  public static final int inicio = 2;
  public static final int entre = 9;
  public static final int real = 11;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int abre_parentesis = 15;
  public static final int raiz = 21;
  public static final int asigna = 10;
  public static final int entero = 12;
  public static final int fin = 3;
  public static final int mas = 6;
  public static final int var = 14;
  public static final int mayor = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "inicio",
  "fin",
  "imprime",
  "finSent",
  "mas",
  "menos",
  "por",
  "entre",
  "asigna",
  "real",
  "entero",
  "cadena",
  "var",
  "abre_parentesis",
  "cierra_parentesis",
  "iguala",
  "mayor",
  "menor",
  "substra",
  "raiz"
  };
}

